config/routes.rb
Rails.application.routes.draw do
  resources :hamams
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hamam.rb
class Hamam < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hamams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/hamams_controller.rb
class HamamsController < ApplicationController
  before_action :set_hamam, only: [:show, :edit, :update, :destroy]
  after_action :authorize_hamam, only: [ :show, :new, :create, :edit, :update ]

  # GET /hamams
  def index
    @hamams = policy_scope(Hamam)
  end

  # GET /hamams/1
  def show; end

  # GET /hamams/new
  def new
    @hamam = Hamam.new
  end

  # GET /hamams/1/edit
  def edit
  end

  # POST /hamams
  def create
    @hamam = Hamam.new(hamam_params)
    @hamam.user = current_user
    if @hamam.save
      redirect_to @hamam, notice: 'Hamam was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /hamams/1
  def update
    if @hamam.update(hamam_params)
      redirect_to @hamam, notice: 'Hamam was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /hamams/1
  def destroy
    authorize_hamam
    @hamam.destroy
    redirect_to hamams_url, notice: 'Hamam was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hamam
      @hamam = Hamam.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hamam_params
      params.require(:hamam).permit(:name, :user_id)
    end

    def authorize_hamam
      authorize @hamam
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hamams/_form.html.erb
<%= simple_form_for(@hamam) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hamams/edit.html.erb
<h1>Editing Hamam</h1>

<%= render 'form', hamam: @hamam %>

<%= link_to 'Show', @hamam %> |
<%= link_to 'Back', hamams_path %>

app/views/hamams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hamams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hamams.each do |hamam| %>
      <tr>
        <td><%= hamam.name %></td>
        <td><%= hamam.user.email %></td>
        <td><%= link_to 'Show', hamam %></td>
        <% if policy(hamam).edit? %>
        <td><%= link_to 'Edit', edit_hamam_path(hamam) %></td>
        <td><%= link_to 'Destroy', hamam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hamam', new_hamam_path %>

app/views/hamams/new.html.erb
<h1>New Hamam</h1>

<%= render 'form', hamam: @hamam %>

<%= link_to 'Back', hamams_path %>

app/views/hamams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hamam.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @hamam.user.email %>
</p>

<% if policy(@hamam).edit?  %>
  <%= link_to 'Edit', edit_hamam_path(@hamam) %>
<% end %> |
<%= link_to 'Back', hamams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HamamsWithPunditIstanbul</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.email, "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>